// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface StoryblokFooter {
  content?: string;
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokGlobal {
  header?: StoryblokHeader[];
  footer?: StoryblokFooter[];
  component: "global";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokHeader {
  content?: string;
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokImage {
  image: StoryblokAsset;
  component: "image";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokPage {
  body?: (
    | StoryblokFooter
    | StoryblokGlobal
    | StoryblokHeader
    | StoryblokImage
    | StoryblokPage
    | StoryblokRichText
    | StoryblokSeoFields
  )[];
  seo?: StoryblokSeoFields[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokRichText {
  content?: StoryblokRichtext;
  component: "rich_text";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokSeoFields {
  meta_title?: string;
  meta_description?: string;
  canonical_url?: string;
  og_image?: StoryblokAsset;
  meta_robots?: "index,follow" | "noindex,follow" | "index,nofollow" | "noindex,nofollow";
  component: "seo_fields";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = StoryblokGlobal | StoryblokPage;
