// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
export interface StoryblokPage {
  body?: StoryblokPage[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = StoryblokPage;
