// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext, StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface StoryblokFooter {
  column_one_group?: unknown;
  column_one_title?: string;
  column_one?: StoryblokLink[];
  column_two_group?: unknown;
  column_two_title?: string;
  column_two?: StoryblokLink[];
  column_three_group?: unknown;
  column_three_title?: string;
  column_three?: StoryblokLink[];
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokGlobal {
  header?: StoryblokHeader[];
  footer?: StoryblokFooter[];
  component: "global";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokHeader {
  content?: string;
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokLink {
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  text?: string;
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokPage {
  body?: (StoryblokRichText | StoryblokSeoFields | StoryblokLink)[];
  seo?: StoryblokSeoFields[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokRichText {
  content?: StoryblokRichtext;
  component: "rich_text";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokSeoFields {
  meta_title?: string;
  meta_description?: string;
  canonical_url?: string;
  og_image?: StoryblokAsset;
  meta_robots?: "index,follow" | "noindex,follow" | "index,nofollow" | "noindex,nofollow";
  component: "seo_fields";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = StoryblokGlobal | StoryblokPage;
